const states = [
    { "StateID": 135, "Statename": "Andaman & Nicobar Is" },
    { "StateID": 128, "Statename": "Andhra Pradesh" },
    { "StateID": 112, "Statename": "Arunachal Pradesh" },
    { "StateID": 118, "Statename": "Assam" },
    { "StateID": 110, "Statename": "Bihar" },
    { "StateID": 104, "Statename": "Chandigarh" },
    { "StateID": 122, "Statename": "Chhattisgarh" },
    { "StateID": 126, "Statename": "Dadra & Nagar Haveli" },
    { "StateID": 125, "Statename": "Daman & Diu" },
    { "StateID": 107, "Statename": "Delhi" },
    { "StateID": 130, "Statename": "Goa" },
    { "StateID": 124, "Statename": "Gujarat" },
    { "StateID": 106, "Statename": "Haryana" },
    { "StateID": 102, "Statename": "Himachal Pradesh" },
    { "StateID": 101, "Statename": "Jammu & Kashmir" },
    { "StateID": 120, "Statename": "Jharkhand" },
    { "StateID": 129, "Statename": "Karnataka" },
    { "StateID": 132, "Statename": "Kerala" },
    { "StateID": 123, "Statename": "Madhya Pradesh" },
    { "StateID": 127, "Statename": "Maharashtra" },
    { "StateID": 114, "Statename": "Manipur" },
    { "StateID": 117, "Statename": "Meghalaya" },
    { "StateID": 115, "Statename": "Mizoram" },
    { "StateID": 113, "Statename": "Nagaland" },
    { "StateID": 121, "Statename": "Orissa" },
    { "StateID": 134, "Statename": "Pondicherry" },
    { "StateID": 103, "Statename": "Punjab" },
    { "StateID": 108, "Statename": "Rajasthan" },
    { "StateID": 111, "Statename": "Sikkim" },
    { "StateID": 133, "Statename": "Tamil Nadu" },
    { "StateID": 137, "Statename": "Telangana" },
    { "StateID": 116, "Statename": "Tripura" },
    { "StateID": 109, "Statename": "Uttar Pradesh" },
    { "StateID": 105, "Statename": "Uttarakhand" },
    { "StateID": 119, "Statename": "West Bengal" }
  ]

  module.exports = states
  