const https = require("https");
const fs = require("fs");

const result = [];

searchOptionsForTataAig = [
    { "state": "ANDAMAN AND NICOBAR", "cities": ["0", "PORT BLAIR"] },
    {
      "state": "ANDHRA PRADESH",
      "cities": [
        "0",
        "AHMEDNAGAR",
        "AMALAPURAM",
        "ANANTAPUR",
        "ANAPARTHI",
        "BHIMAVARAM",
        "CHALLAPALLI",
        "CHENNAI",
        "CHILAKALURIPET",
        "CHIRALA",
        "CHITTOOR",
        "ELURU",
        "GIDDALUR",
        "GUDIVADA",
        "GUNTUR",
        "HINDUPUR",
        "JAGGAMPETA",
        "JANGAREDDYGUDEM ",
        "KADAPA",
        "KAKINADA",
        "KANDUKUR ",
        "KAVALI",
        "KOVILPATTI",
        "KURNOOL",
        "MACHILIPATNAM",
        "MANDAPETA",
        "MARKAPUR",
        "NAIDUPETA",
        "NANDYAL",
        "NARASARAOPET",
        "NARSAPUR",
        "NELLORE",
        "ONGOLE",
        "PALAKOL",
        "PIDUGURALLA",
        "PRAKASHAM",
        "RAJAHMUNDRY",
        "RAVULAPALEM",
        "SRIKAKULAM",
        "SRIKALAHASTI",
        "TADEPALLIGUDEM",
        "TANUKU",
        "TENALI",
        "TIRUPATI",
        "TIRUVRU",
        "TUNI",
        "VIJAYAWADA",
        "VISAKHAPATNAM",
        "VIZIANAGARAM"
      ]
    },
    { "state": "ARUNACHAL PRADESH", "cities": ["0", "NAHARLAGUN"] },
    {
      "state": "ASSAM",
      "cities": [
        "0",
        "BARPETA",
        "BONGAIGAON",
        "DARRANGA",
        "DHUBRI",
        "DIBRUGARH",
        "GOALPARA",
        "GUWAHATI",
        "JORHAT",
        "KOKRAJHAR",
        "LAKHIMPUR",
        "NAGAON",
        "NALBARI",
        "RANGIA",
        "SILCHAR",
        "SIVASAGAR",
        "TEZPUR",
        "TINSUKIA"
      ]
    },
    {
      "state": "BIHAR",
      "cities": [
        "0",
        "BARPETA",
        "BONGAIGAON",
        "DARRANGA",
        "DHUBRI",
        "DIBRUGARH",
        "GOALPARA",
        "GUWAHATI",
        "JORHAT",
        "KOKRAJHAR",
        "LAKHIMPUR",
        "NAGAON",
        "NALBARI",
        "RANGIA",
        "SILCHAR",
        "SIVASAGAR",
        "TEZPUR",
        "TINSUKIA"
      ]
    },
    { "state": "CHANDIGARH", "cities": ["0", "CHANDIGARH"] },
    {
      "state": "CHHATTISGARH",
      "cities": [
        "0",
        "AMBIKAPUR",
        "BALODA BAZAR",
        "BASNA",
        "BHILAI",
        "BILASPUR",
        "CHAMPA",
        "DHAMTARI",
        "DURG",
        "GURGAON",
        "JAGDALPUR",
        "KORBA",
        "RAIGARH",
        "RAIPUR",
        "RAJNANDGAON"
      ]
    },
    { "state": "DADRA AND NAGAR HAVELI", "cities": ["0", "SILVASSA"] },
    { "state": "DELHI", "cities": ["0", "NEW DELHI"] },
    {
      "state": "GOA",
      "cities": [
        "0",
        "BARDEZ",
        "BHOPAL",
        "BICHOLIM",
        "CANDOLIM",
        "MAPUSA",
        "MARGAO",
        "PANJIM",
        "PERNEM",
        "PONDA",
        "VALPOI",
        "VASCODI GAMA"
      ]
    },
    {
      "state": "GUJARAT",
      "cities": [
        "0",
        "AHMEDABAD",
        "AMRELI",
        "ANAND",
        "ANKLESHWAR",
        "BARDOLI",
        "BAREJA",
        "BECHARAJI",
        "BENGALURU",
        "BHACHAU",
        "BHARUCH",
        "BHAVNAGAR",
        "BHUJ",
        "BOTAD",
        "DABHOI",
        "DAHOD",
        "DEESA",
        "DHOLKA",
        "GANDHIDHAM",
        "GANDHINAGAR",
        "GODHRA",
        "GONDAL",
        "GUNTUR",
        "HALOL",
        "HIMMATNAGAR",
        "JAM KHAMBALIYA",
        "JAMNAGAR",
        "JUNAGADH",
        "KADI",
        "KALOL",
        "KARAMSAD",
        "KESHOD",
        "KHAMBHAT",
        "KHEDA",
        "KODINAR",
        "KOSAMBA",
        "KUTCH",
        "MAHUVA",
        "MEHSANA",
        "MORBI",
        "MUNDRA",
        "NADIAD",
        "NAVSARI",
        "PADRA",
        "PALANPUR",
        "PARDI",
        "PATAN",
        "RAJKOT",
        "SURAT",
        "SURENDRANAGAR",
        "UDHNA",
        "UNA",
        "VADODARA",
        "VALSAD",
        "VAPI",
        "VERAVAL",
        "VYARA"
      ]
    },
    {
      "state": "HARYANA",
      "cities": [
        "0",
        "AMBALA",
        "BAHADURGARH",
        "BALLABGARH",
        "BHIWANI",
        "BULANDSHAHR",
        "CHARKHI DADRI",
        "FARIDABAD",
        "FATEHABAD",
        "GOHANA",
        "GURGAON",
        "HISAR",
        "HODAL",
        "JAIPUR",
        "JHAJJAR",
        "JIND",
        "KAITHAL",
        "KARNAL",
        "KURUKSHETRA",
        "MAHENDRAGARH",
        "NARNAUL",
        "PALWAL",
        "PANCHKULA",
        "PANIPAT",
        "PINJORE",
        "PITHAPURAM",
        "REWARI",
        "ROHTAK",
        "SHAHABAD",
        "SIRSA",
        "SONIPAT",
        "TRIVANDRUM",
        "YAMUNANAGAR"
      ]
    },
    {
      "state": "HIMACHAL PRADESH",
      "cities": [
        "0",
        "BHUJ",
        "HAMIRPUR",
        "KANGRA",
        "KULLU",
        "MANALI",
        "MANDI",
        "NALAGARH",
        "PAONTA SAHIB",
        "SHIMLA",
        "SIRMORE",
        "SOLAN",
        "SUNDARNAGAR",
        "UNA"
      ]
    },
    {
      "state": "JAMMU AND KASHMIR",
      "cities": [
        "0",
        "ANANTNAG",
        "BARAMULLA",
        "JAMMU",
        "KATHUA",
        "PULWAMA",
        "REASI",
        "SOPORE",
        "SRINAGAR"
      ]
    },
    {
      "state": "JHARKHAND",
      "cities": [
        "0",
        "BAGODAR",
        "BOKARO",
        "DALTONGANJ",
        "DEOGHAR",
        "DHANBAD",
        "GIRIDIH",
        "GODDA",
        "GUMLA",
        "GURGAON",
        "HAZARIBAGH",
        "JAMSHEDPUR",
        "KODARMA",
        "LOHARDAGA",
        "RAMGARH",
        "RANCHI",
        "SAHIBGANJ"
      ]
    },
    {
      "state": "KARNATAKA",
      "cities": [
        "0",
        "ARSIKERE",
        "BAGALKOT",
        "BELGAUM",
        "BELLARY",
        "BELTANGADI",
        "BENGALURU",
        "BHATKAL",
        "BIDAR",
        "BIJAPUR",
        "CHAMARAJANAGAR",
        "CHANNAPATNA",
        "CHIKKABALLAPUR",
        "CHIKKAMANGALORE",
        "CHIKKODI",
        "CHINTAMANI",
        "CHITRADURGA",
        "DAVANGERE",
        "DHARWAD",
        "GADAG",
        "GANGAVATHI",
        "GOKAK",
        "GULBARGA",
        "GWALIOR",
        "HASSAN",
        "HAVERI",
        "HOSPET",
        "HUBLI",
        "KADUR",
        "KALABURAGI",
        "KARKALA",
        "KARWAR",
        "KOLAR",
        "KOPPA",
        "KOPPAL",
        "KUNDAPUR",
        "MADIKERI",
        "MALUR",
        "MANDYA",
        "MANGALORE",
        "MANIPAL",
        "MHOW",
        "MYSORE",
        "NIPANI",
        "PUTTUR",
        "RABAKAVI BANAHATI",
        "RAICHUR",
        "RAMANAGARA",
        "RANEBENNUR",
        "SANDUR",
        "SHIMOGA",
        "SIRA",
        "SIRSI",
        "SULLIA",
        "TIPTUR",
        "TUMKUR",
        "UDUPI",
        "UTTARA KANNADA",
        "VIJAYANAGAR"
      ]
    },
    {
      "state": "KERALA",
      "cities": [
        "0",
        "ADOOR",
        "ALAPPUZHA",
        "ALUVA",
        "ANGAMALY",
        "ATTINGAL",
        "CALICUT",
        "CHANGANASSERY",
        "CHAVAKKAD ",
        "CHENGANNUR",
        "CHENNAI",
        "CHERTHALA",
        "COCHIN",
        "EDAPPAL",
        "ERNAKULAM",
        "FEROKE",
        "IDUKKI",
        "IRINJALAKUDA",
        "IRITTY",
        "KANHANGAD",
        "KANJIRAPALLY",
        "KANNUR",
        "KASARAGOD",
        "KOLLAM",
        "KOTTAKKAL",
        "KOTTAYAM",
        "KOZHIKODE",
        "KOZHINJAMPARA",
        "KUNNAMKULAM",
        "MALAPURAM",
        "MANJERI",
        "MANNARKKAD",
        "MAVELIKKARA",
        "MUVATTUPUZHA",
        "OTTAPLAM",
        "PALAKKAD",
        "PANJIM",
        "PATHANAMTHITTA",
        "PATTAMBI",
        "PAYYANUR",
        "PERINTHALMANNA",
        "PERUMBAVOOR",
        "PERUMPILAVU",
        "PONKUNNAM",
        "PONNANI",
        "PORATHISERRY",
        "PUNALUR",
        "TALIPARAMBA",
        "THALASSERY",
        "THALAYOLAPARAMBU",
        "THALIPPARAMBA",
        "THIRUVALLA",
        "THODUPUZHA",
        "THRIPPUNITHURA",
        "THRISSUR",
        "TRIVANDRUM",
        "VADAKARA",
        "VAIKOM",
        "WAYANAD"
      ]
    },
    {
      "state": "MADHYA PRADESH",
      "cities": [
        "0",
        "ANUPPUR",
        "BEED",
        "BETUL",
        "BHOPAL",
        "BURHANPUR",
        "CHHATARPUR",
        "CHHINDWARA",
        "DAMOH",
        "DEWAS",
        "DHAR",
        "GREATER NOIDA",
        "GUNA",
        "GURGAON",
        "GWALIOR",
        "HARIDWAR",
        "HOSHANGABAD",
        "INDORE",
        "JABALPUR",
        "KATNI",
        "KHANDWA",
        "KURAWAR",
        "MANDIDEEP",
        "MANDSAUR",
        "MHOW",
        "PUDUCHERRY",
        "RAISEN",
        "RATLAM",
        "REWA",
        "SATNA",
        "SEHORE",
        "SHAHDOL",
        "SHUJALPUR",
        "TIKAMGARH",
        "UJJAIN",
        "VIDISHA"
      ]
    },
    {
      "state": "MAHARASHTRA",
      "cities": [
        "0",
        "AHMEDNAGAR",
        "AKLUJ",
        "AKOLA",
        "AMALNER",
        "AMRAVATI",
        "ASHTA",
        "AURANGABAD",
        "BARAMATI",
        "BARSHI",
        "BEED",
        "BHANDARA",
        "BHUSAWAL",
        "BULDHANA",
        "CHAKAN",
        "CHANDRAPUR",
        "CHIPLUN",
        "DHULE",
        "GADHINGLAJ",
        "GONDIA",
        "GURGAON",
        "GWALIOR",
        "HINGOLI",
        "ICHALKARANJI",
        "IGATPURI",
        "INDAPUR",
        "ISLAMPUR",
        "JALGAON",
        "JALNA",
        "JAMNER",
        "JAYSINGPUR",
        "KAMPTEE",
        "KANKAVLI",
        "KARAD",
        "KHAMGAON",
        "KHOPOLI",
        "KOLHAPUR",
        "KOPARGAON",
        "LATUR",
        "LONAND",
        "LONAVALA",
        "MALEGAON",
        "MALKAPUR",
        "MANWATH",
        "MIRAJ",
        "MUMBAI",
        "MURTIJAPUR",
        "NAGPUR",
        "NANDED",
        "NANDURBAR",
        "NARAYANGAON",
        "NASHIK",
        "NAVI MUMBAI",
        "NEW PANVEL",
        "NIPHAD",
        "NOIDA",
        "OSMANABAD",
        "PALGHAR",
        "PANDHARPUR",
        "PANVEL",
        "PARATWADA",
        "PARBHANI",
        "PARLI",
        "PAROLA",
        "PEN",
        "PHALTAN",
        "PUNE",
        "RAIGAD",
        "RANGA REDDY",
        "RATNAGIRI",
        "SANGAMNER",
        "SANGLI",
        "SANGOLA",
        "SATANA",
        "SATARA",
        "SAWANTWADI",
        "SHEVGAON",
        "SHIRPUR",
        "SHIRUR",
        "SHIRWAL",
        "SHRIGONDA",
        "SHRIRAMPUR",
        "SINNAR",
        "SOLAPUR",
        "SOLAPUR ",
        "THANE",
        "UDGIR",
        "WARDHA",
        "WASHIM",
        "YAVATMAL"
      ]
    },
    { "state": "MANIPUR", "cities": ["0", "IMPHAL"] },
    { "state": "MEGHALAYA", "cities": ["0", "SHILLONG"] },
    { "state": "MIZORAM", "cities": ["0", "AIZAWL"] },
    { "state": "NAGALAND", "cities": ["0", "DIMAPUR"] },
    {
      "state": "ODISHA",
      "cities": [
        "0",
        "ANGUL",
        "BALASORE",
        "BARGARH",
        "BERHAMPUR",
        "BHADRAK",
        "BHUBANESHWAR",
        "CHOUDWAR",
        "CUTTACK",
        "DHENKANAL",
        "GANJAM",
        "JAGATSINGHPUR",
        "JAJPUR",
        "JHARSUGUDA",
        "KENDRAPARA",
        "KEONJAR",
        "KHORDHA",
        "MAYURBHANJA",
        "NAYAGARH",
        "PURI",
        "RAYAGADA",
        "ROURKELA",
        "SAMBALPUR",
        "SONEPUR"
      ]
    },
    {
      "state": "PONDICHERRY",
      "cities": ["0", "COIMBATORE", "MADAGADIPET", "PUDUCHERRY"]
    },
    {
      "state": "PUNJAB",
      "cities": [
        "0",
        "ABOHAR",
        "AHMEDGARH",
        "AMRITSAR",
        "BARNALA",
        "BATALA",
        "BATHINDA",
        "CHANDIGARH",
        "DERABASSI",
        "DORAHA",
        "FARIDKOT",
        "FATEHGARH SAHIB",
        "FAZILKA",
        "FEROZEPUR",
        "GURDASPUR",
        "HOSHIARPUR",
        "JAGRAON",
        "JALANDHAR",
        "KAPURTHALA",
        "KHANNA",
        "KHARAR",
        "KOTKAPURA",
        "KURALI",
        "LUDHIANA",
        "MALERKOTLA",
        "MANSA",
        "MOGA",
        "MOHALI",
        "MUKTSAR",
        "NABHA",
        "NAWANSHAHR",
        "PATHANKOT",
        "PATIALA",
        "PHAGWARA",
        "RAJPURA",
        "ROPAR",
        "SAMANA",
        "SANGRUR",
        "TARN TARAN",
        "URMAR TANDA",
        "ZIRAKPUR"
      ]
    },
    {
      "state": "RAJASTHAN",
      "cities": [
        "0",
        "AJMER",
        "ALWAR",
        "BALOTRA",
        "BANDIKUI",
        "BANSWARA",
        "BARAN",
        "BAREILLY",
        "BARMER",
        "BEAWAR",
        "BHARATPUR",
        "BHILWARA",
        "BHIWADI",
        "BIKANER",
        "BUNDI",
        "CHITTAURGARH",
        "CHURU",
        "DUNGARPUR",
        "HANUMANGARH",
        "JAIPUR",
        "JAISALMER",
        "JALORE",
        "JHALAWAR",
        "JHUNJHUNUN",
        "JODHPUR",
        "KOTA",
        "KOTPUTLI",
        "MAKRANA",
        "MOUNT ABU",
        "MUKTAINAGAR",
        "NAGAUR",
        "PALI",
        "PHULERA",
        "PRATAPGARH",
        "RAJSAMAND",
        "SAGWARA",
        "SARDARSHAHAR",
        "SIKAR",
        "SIROHI",
        "SRI GANGANAGAR",
        "TONK",
        "UDAIPUR"
      ]
    },
    { "state": "SIKKIM", "cities": ["0", "GANGTOK"] },
    {
      "state": "TAMIL NADU",
      "cities": [
        "0",
        "ARIYALUR",
        "BHIWANI",
        "CHENNAI",
        "COIMBATORE",
        "COONOOR",
        "CUDDALORE",
        "DEVAKOTTAI",
        "DHARMAPURI",
        "DINDIGUL",
        "ERODE",
        "GOBICHETTIPALAYAM",
        "HOSUR",
        "INDORE",
        "JALNA",
        "KALLAKURICHI",
        "KANCHIPURAM",
        "KANYAKUMARI",
        "KARAIKUDI",
        "KARUR",
        "KOLKATA",
        "KOMARAPALAYAM",
        "KOSAPET",
        "KOVILPATTI",
        "KRISHNAGIRI",
        "KUMBAKONAM",
        "MADURAI",
        "MANAPPARAI",
        "METTUPALAYAM",
        "NAGAPATTINAM",
        "NAGERCOIL",
        "NAMAKKAL",
        "ODDANCHATRAM ",
        "OOTY",
        "PATTUKKOTTAI",
        "PERAMBALUR",
        "PERIYAKULAM",
        "POLLACHI",
        "PUDUKKOTTAI",
        "RAMANATHAPURAM",
        "RAMNAD",
        "RASIPURAM",
        "SALEM",
        "SIVAGANGA",
        "SIVAKASI",
        "SRIPERUMBUDUR",
        "THANJAVUR",
        "THENI",
        "THIRUVALLUR",
        "THIRUVARUR",
        "THOOTHUKUDI",
        "THUCKALAY",
        "TIRUKOVILUR",
        "TIRUNELVELI",
        "TIRUPATI",
        "TIRUPATTUR",
        "TIRUPUR",
        "TIRUVANNAMALAI",
        "TIRUVARUR",
        "TRICHY",
        "TUTICORIN",
        "UDAMELPET",
        "VELLORE",
        "VILLUPURAM",
        "VIRUDHUNAGAR",
        "WARANGAL"
      ]
    },
    {
      "state": "TELANGANA",
      "cities": [
        "0",
        "ADILABAD",
        "BHONGIR",
        "DEVARAKONDA",
        "GOKAK",
        "HANAMKONDA",
        "HYDERABAD",
        "JAGITIAL",
        "JAMMIKUNTA",
        "KAMAREDDY ",
        "KARIMNAGAR",
        "KHAMMAM",
        "KODAD",
        "KOTHAGUDEM",
        "MAHABUBABAD",
        "MAHABUBNAGAR",
        "MANCHERIAL",
        "MEDAK",
        "MIRYALAGUDA",
        "NALGONDA",
        "NIRMAL",
        "NIZAMABAD",
        "RANGA REDDY",
        "SANGAREDDY",
        "SECUNDERABAD",
        "SIDDIPET",
        "VIKARABAD",
        "WARANGAL",
        "ZAHEERABAD"
      ]
    },
    { "state": "TRIPURA", "cities": ["0", "AGARTALA"] },
    {
      "state": "UTTAR PRADESH",
      "cities": [
        "0",
        "AGRA",
        "ALIGARH",
        "AMBEDKAR NAGAR",
        "AMROHA",
        "ANKLESHWAR",
        "AURAIYA",
        "AZAMGARH",
        "BAGHPAT",
        "BALLIA",
        "BARA",
        "BARABANKI",
        "BARAUT",
        "BAREILLY",
        "BHADOHI",
        "BIJNOR",
        "BUDAUN",
        "BULANDSHAHR",
        "DEORIA",
        "ETAWAH",
        "FAIZABAD",
        "FATEHPUR",
        "FIROZABAD",
        "GHAZIABAD",
        "GONDA",
        "GORAKHPUR",
        "GREATER NOIDA",
        "HAPUR",
        "HARDOI",
        "HATHRAS",
        "HAZARIBAGH",
        "JAUNPUR",
        "JEWAR",
        "JHANSI",
        "KANPUR",
        "KHERI",
        "KHURJA",
        "LAKHIMPUR",
        "LALITPUR",
        "LUCKNOW",
        "MAHARAJGANJ",
        "MANAPPARAI",
        "MATHURA",
        "MAU",
        "MEERUT",
        "MIRZAPUR",
        "MODINAGAR",
        "MORADABAD",
        "MUGHALSARAI",
        "MUZAFFARNAGAR",
        "NOIDA",
        "PILLIBHIT ",
        "PRAYAGRAJ",
        "RAI BARELI",
        "RAMPUR",
        "SAHARANPUR",
        "SHAHJAHANPUR",
        "SHAMLI",
        "SIDDHARTHNAGAR",
        "SIKANDRABAD",
        "SITAPUR",
        "SONEBHADRA",
        "SULTANPUR",
        "UNNAO",
        "VARANASI",
        "VELLORE"
      ]
    },
    {
      "state": "UTTARAKHAND",
      "cities": [
        "0",
        "ALMORA",
        "DEHRADUN",
        "HALDWANI",
        "HARIDWAR",
        "KASHIPUR",
        "KHATIMA",
        "KOTA",
        "NAINITAL",
        "RISHIKESH",
        "ROORKEE",
        "RUDRAPUR",
        "SITARGANJ",
        "UDHAM SINGH NAGAR"
      ]
    },
    {
      "state": "WEST BENGAL",
      "cities": [
        "0",
        "ANDAL",
        "ASANSOL",
        "BANDEL",
        "BANKURA",
        "BARUIPUR",
        "BERHAMPORE",
        "BIRBHUM",
        "BURDWAN",
        "CHINSURAH",
        "COOCHBEHAR",
        "DARJILING",
        "DUBRAJPUR",
        "DURGAPUR",
        "HOOGHLY",
        "HOWRAH",
        "KATWA",
        "KHARAGPUR",
        "KOLKATA",
        "KOTTAYAM",
        "KRISHNANAGAR",
        "MADHYAMGRAM",
        "MALDA",
        "MALDA ",
        "MURSHIDABAD",
        "NADIA",
        "NAIHATI",
        "NORTH 24 PARGANAS",
        "PASCHIM MIDNAPUR",
        "PURBA MIDNAPUR",
        "PURULIA",
        "RANIGUNJ",
        "SANTIPUR",
        "SERAMPORE",
        "SILIGURI",
        "SODEPUR",
        "SOUTH 24 PARGANAS",
        "TARAKESHWAR",
        "UTTAR DINAJPUR"
      ]
    }
  ]
  

async function selectStateAndGetCityOptions(stateForCity) {
    return stateForCity.cities;
}

async function selectCityAndGetHospitalDetails(cities) {
    const url = `https://www.tataaig.com/servicing/api/hospitals?pageNo=1&city=${cities}`;

    return new Promise((resolve, reject) => {
        https.get(url, function (response) {
            let data = "";

            response.on("data", function (chunk) {
                data += chunk;
            });

            response.on("end", function () {
                try {
                    const hospitalList = JSON.parse(data);
                    console.log(hospitalList.data, 'line no 60....');
                    resolve(hospitalList.data);
                } catch (error) {
                    reject("Error parsing JSON: " + error.message);
                }
            });
        }).on("error", function (error) {
            reject("Error making HTTP request: " + error.message);
        });
    });
}

async function main(searchOptions) {
    try {
        for (let i = 0; i < searchOptions.length; i++) {
            const cityOptions = await selectStateAndGetCityOptions(searchOptions[i]);
            console.log(`City Options for State ${searchOptions[i].state}:`, cityOptions);

            for (let j = 1; j < cityOptions.length; j++) {
                console.log(cityOptions[j], "second for loop")
                try {
                    const hospitalDetails = await selectCityAndGetHospitalDetails(cityOptions[j]);
                    console.log(`Hospital Details for City ${cityOptions[j]}:`, hospitalDetails);
                    if(hospitalDetails.count === 0){
                        result.push(null)
                    }else{
                        result.push(...hospitalDetails.data)
                    }
                 
                    fs.writeFileSync("./tataaig/tataaig.json", JSON.stringify(result));
                } catch (error) {
                    console.error("Error fetching hospital details:", error);
                }
            }
        }
    } catch (error) {
        console.error("Error navigating to the page:", error);
    }
}

main(searchOptionsForTataAig);
